---
title: "Course support"
---

Most of you will need help at some point and we want to make sure you can identify when that is without getting too frustrated and feel comfortable seeking help.

## Lectures and labs

If you have a question during lecture or lab, feel free to ask it!
There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.

## Office hours

The teaching team is here to help you be successful in the course.
You are encouraged to attend office hours during the times posted on the home page to ask questions about the course content and assignments.
A lot of questions are most effectively answered in-person, so office hours are a valuable resource.
I encourage each and every one of you to take advantage of this resource!
Make a pledge to stop by office hours at least once during the first three weeks of class.
If you truly have no questions to ask, just stop by and say hi and introduce yourself.
You can find a list of everyone's office hours [here](/course-team.html).

## Ed Discussion

Have a question that can't wait for office hours?
Prefer to write out your question in detail rather than asking in person?
Ed Discussion is the best venue for these!
There is a chance another student has already asked a similar question, so please check the other posts on Ed Discussion before asking a new question.
If you know the answer to a question that is posted, I encourage you to respond!

## Email

Please refrain from emailing any course content questions (those should go to Slack), and only use email for questions about personal matters that may not be appropriate for the public course forum (e.g., illness, accommodations, etc.).
For such matters, you may email Dr. Mine Çetinkaya-Rundel at [mc301\@duke.edu](mailto:mc301@duke.edu).

If there is a question that's not appropriate for the public forum, you are welcome to email me directly.
**If you email me, please include "STA 313" in the subject line.** Barring extenuating circumstances, I will respond to STA 313 emails within 48 hours Monday - Friday.
Response time may be slower for emails sent Friday evening - Sunday.

## Academic support

There are times may need help with the class that is beyond what can be provided by the teaching team.
In those instances, I encourage you to visit the Academic Resource Center.
The [Academic Resource Center (the ARC)](https://arc.duke.edu) offers services to support students academically during their undergraduate careers at Duke.
The ARC can provide support with time management, academic skills and strategies, course-specific tutoring, and more.
ARC services are available free to all Duke undergraduate student studying any discipline.
You can contact the Academic Resource Center by phone at (919) 684-5917, by email at [theARC\@duke.edu](mailto:theARC@duke.edu), or by visiting <https://arc.duke.edu>.
The [TWP Writing Studio](https://twp.duke.edu/twp-writing-studio) provides attentive, non-evaluative readers who can help students see whether they’re expressing ideas in ways that are clear to someone outside our class.
Consults with the Writing Studio can be productive at any stage in a student’s process, including before writing has begun.
Visit <https://twp.duke.edu/twp-writing-studio> to learn more and to schedule an in- person or online appointment.

## Mental health and wellness

Duke is committed to holistic student wellbeing, which includes one’s mental, emotional, and physical health.
The university offers resources to help students manage daily stress, to encourage intentional self-care, and to access just-in-time support.
If you find you need support, your mental and/or emotional health concerns are impacting your day-to-day activities, your academic performance, or you need someone to talk to, the resources below are available to you:

-   [DukeReach](https://students.duke.edu/wellness/dukereach/): DukeReach provides comprehensive outreach services to support students in managing all aspects of wellbeing, including referrals and follow-up services for students who are experiencing significant challenges related to mental health, physical health, social adjustment, and/or a variety of other stressors.
    You can contact the DukeReach team at [dukereach\@duke.edu](mailto:dukereach@duke.edu).

-   [Counseling and Psychological Services (CAPS)](https://students.duke.edu/wellness/caps/): CAPS offers counseling services to Duke students including virtual appointments, and referrals in the community.
    You do not need an appointment for an initial assessment.
    You may walk in or call 919-660-1000 to get started.
    Hours: Monday-Friday 9:00am - 4:00pm.
    After hours counseling services are available at no additional cost to students, you can call: 919-660-1000 Option 2.

-   [TimelyCare (formerly known as Blue Devils Care)](https://app.timelycare.com/auth/login?campaign=vanitylink): TimelyCare is an online platform that is a convenient, confidential, and free way for Duke students to receive 24/7 mental health support through TalkNow and scheduled counseling.

-   [Duke Student Health](https://students.duke.edu/wellness/studenthealth/): Student Health offers a wide range of healthcare services for all Duke students, many of which are covered by the student health fee.
    To make an appointment call (919) 681-9355.
    Hours: Monday - Friday, 8am - 4:30pm, Thursday 9am - 4:30pm.
    Closed from 12-12:30 each day.

## Course costs

-   **Textbooks:** The textbooks for this course are freely available on the web.
-   **Laptops:** Each student is expected to have a laptop they can bring to each lecture and lab.

If you are having difficulty with the textbook and supply costs associated with this course, here are some resources:

-   [Karsh Office of Undergraduate Financial Support](https://financialaid.duke.edu): Regardless of your aid package, Karsh offers loans and resources for connecting students with campus programs that might help alleviate course costs.
-   [DukeLIFE](https://dukelife.duke.edu/academic-support/course-materials-assistance/): The Course Material Assistance program offers assistance for eligible students. Students who are eligible for DukeLIFE benefits are notified prior to the start of the semester; program resources are limited.
-   [Duke Libraries](https://library.duke.edu/course-support/course-reserves/textbooks): The library’s Top Textbook Program allows you to rent some textbook for 3 hours at a time.
-   [Duke Link](https://link.duke.edu): You can reserve rental equipment from the Link for course- specific technology needs, such as a Digital Voice Recorder, HD Video Camera, TI-84 Plus CE, DSLR camera kit, Tripod, Shotgun Mic, iPad Mini 4, Handheld Projector, or GoPro.

Highly-aided students who have limited access to computers may request loaner laptops through the [LIFE Loaner Laptop Program](https://dukelife.duke.edu/academic-support/loaner-laptop-program/).
Please note that supplies are limited.

## Assistance with Zoom or Canvas

For technical help with Zoom or Canvas, contact the Duke OIT Service Desk at [oit.duke.edu/help](https://oit.duke.edu/help).
You can also access the self-service help documentation for Zoom [here](https://oit.duke.edu/help/articles/kb0029318) and for Canvas [here](https://go.canvas.duke.edu/get-help/).

Zoom will be used for online office hours as well as as a backup option should we need to hold the course online instead of in person.

Note that we will be making minimal use of Canvas in this course (primarily for announcements, Ed Discussion and gradebook).
All assignment submissions will take place on GitHub.
