---
title: "FAQ"
---

## Can I use a local install of Positron instead of using Posit Workbench?

Sure! But you will need to install a specific versions of R, Python, and Positron for everything to work as expected. You will also need to install the R and Python packages we're using as well as have Git installed on your computer. These are not extremely challenging things to get right, but they are not trivial either, particularly on certain operating systems. Myself and the TAs are always happy to provide help with any computational issues that arise when you're working in Posit Workbench we have provided for you. If you're working on your local setup, we can't guarantee being able to resolve your issues, though we're happy to try.

If you want to take this path, here is what you need to do:

-   Download and install Positron: <https://positron.posit.co/download.html>
-   Download and install R 4.5.2: <https://cran.r-project.org/>
-   Download and install Python 3.14.2: <https://www.python.org/downloads/>
-   Install Git: <https://happygitwithr.com/install-git.html>
-   Install any necessary packages with `install.packages("___")` or `pip install ___` as needed.

And I'd like to reiterate again that successful installation of these software is **not** a learning goal of this course. So if any of this seems tedious or intimidating in any way, just use the computing environment we have set up for you. More on that [here](/computing-access.html).
