---
title: "Computing setup"
---

We will use R and Python in this course and use Positron as our IDE.
You will also need Git.

# Step 1 - Set up

## Option 1 - Local installation

1. Dowload and install R: Follow these steps if you do not already have R installed or you need to update your version.

    - Go to <https://cran.r-project.org/>.
    - Download R 4.5.2 for your operating system.
    - Follow the installation instructions.

Steps for installing Python will be provided later in the course.

2. Install Positron: Follow these steps if you do not already have Positron installed or you need to update your version.

    - Go to <https://positron.posit.co/download.html>.
    - Accept the license agreement by checking the box.
    - Download Positron Positron-2026.01.0-147 for your operating system.
    - Follow the installation instructions.

3. Install Git: Follow these steps if you do not already have Git installed. You can check if Git is already installed by opening a shell (e.g., Terminal) and typing `which git` and/or `git --version`. 

    - If Git is installed, you will see the path to the Git executable and/or the version number. You're good to go!
    - If not, you might see an error message indicating that the command is not found, e.g., `git: command not found`. Follow the steps at <https://happygitwithr.com/install-git> for your operating system.

## Option 2 - Server access

If you are unable to install the software locally on your computer, you can use the departmental Posit workbench server at <https://rstudio.stat.duke.edu>.

Note that this requires Duke Net ID log in. Additionally, if you're not on the DukeBlue network, you will need to connect to [Duke's VPN](https://oit.duke.edu/service/vpn/).

Once you're logged in with your Duke Net ID, click on *New Session* and select Positron. You might need to wait a bit for the session to launch, please be patient.

# Step 2 - Test

## Step 2.1 - Create a GitHub repository from the template

- Go to <https://github.com/vizdata-s26/test-setup>.
- Click on the green button on the top right corner that says "Use this template" and choose *Create a new repository*.
- In the next window, 
    1. General: Owner should be `vizdata-s26` and repository name should be `test-setup-YOUR-GITHUB-USERNAME` (replace `YOUR-GITHUB-USERNAME` with your actual GitHub username), e.g., mine is `test-setup-mine-cetinkaya-rundel`, if your GitHub username is `dataVizAddict` it would be `test-setup-dataVizAddict`. Under "Description", you can write "Test repository for computing setup".
    2. Configuration: Keep it as *Private*.
    3. Jumpstart your project with Copilot (optional), you can leave it blank.
  And then click on *Create repository*.

## Step 2.2 - Clone the repository

- Open Positron.
- In the top right corner, click on *New -> New Folder From Git...*
- In the pop-up window, paste the URL of your newly created repository. You can find it by going to your repository on GitHub and clicking on the green *Code* button, then copying the URL under either HTTPS or SSH, depending on which GitHub authentication you have set up.

::: {.callout-tip collapse="true"}
## Not sure which authentication method to use?

Option 1: If you're using a **local installation of Positron**, HTTPS is usually easier to set up.

- In your browser, log in to GitHub.
- In Positron, in the Console, run `usethis::create_github_token()`. This takes you to a pre-filled form to create a new PAT (personal access token). Click *Generate token*. Then, copy this token. Important note -- you won't be able to see it again once you leave the page.
- Then, put your PAT into the local Git credential store by running `gitcreds::gitcreds_set()` in the Console in Positron. This will prompt you to enter your GitHub username and the PAT you just created. Paste it and hit Enter.


Option 2: If you're using the **departmental Posit workbench server**, you should set up SSH. 

- Run `credentials::ssh_setup_github()` in the Console in Positron and follow the instructions.
- The function will first prompt you to create an SSH key pair if one does not already exist.

```
## No SSH key found. Generate one now? 
## 
## 1: Yes
## 2: No
## 
## Selection: 
```

Select Yes by entering 1 and hitting enter. The key pair will be generated and the resulting public key will be printed,

```
## Generating new RSA keyspair at: /home/guest/.ssh/id_rsa
## Your public key:
## 
##  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5KwynraqqA4O91nOBtyuJMhYoeCAroSv7yC/GTXcjXsBvgYAlL0PCurJP7uRFbvkUaoBvuaGohR1qDlYNNWzH5FBDqftY+o35otq88mhDUaOmCzuik+MCLGiS/hp2D+5imc1Vqjabvk3fexMr7qkHrJE04vB/ZzI0iZzoZ0zGIJSistNODhrt6jCK7OzPFb4/lGGDxp0+vaGKeXIQGGdUwvMUD+HyNqTgO+g7rcdgmnVMWhhLH8uNb7tpQwDbRQu1h4R+xHO9JMHxFUz2cX4Du6GaQXuYLX3p8X276Nl8CU/V2R4CbGMJwO0Z0jcY8CVUhYBOIJsuS1a5ttHSoLCx 
```

You will then be prompted to enter this public key to GitHub, via the provided link, you can also select Yes here to have the function open a browser window directly to this page.

```
## Please copy the line above to GitHub: https://github.com/settings/ssh/new
## Would you like to open a browser now? 
## 
## 1: Yes
## 2: No
## 
## Selection:
```

- Enter a meaningful name for the key and then copy and paste the entire public key. Once finished, you can click the green Add SSH key button. This key should now show in the list of GitHub SSH keys on <https://github.com/settings/keys>.

:::
