---
title: Women scientists and timelines
subtitle: AE 05
---

# Setup

```{r}
#| label: load-packages
#| message: false
library(tidyverse)
library(popthemes) # pak::pak("johnmackintosh/popthemes")
```

# Data

Read:

```{r}
#| label: scientists-gantt-read
#| message: false
professions <- read_csv("data/scientists/professions.csv")
dates <- read_csv("data/scientists/dates.csv")
works <- read_csv("data/scientists/works.csv")
```

Join:

```{r}
#| label: scientists-gantt-join
scientists <- professions |>
  left_join(dates, by = join_by(name)) |>
  left_join(works, by = join_by(name))

scientists
```

Fill in the blanks and reshape:

```{r}
#| label: scientists-gantt-transform
#| message: false
scientists_longer <- scientists |>
  mutate(
    birth_year = case_when(
      name == "Ada Lovelace" ~ 1815,
      name == "Marie Curie" ~ 1867,
      TRUE ~ birth_year
    ),
    death_year = case_when(
      name == "Ada Lovelace" ~ 1852,
      name == "Marie Curie" ~ 1934,
      TRUE ~ death_year
    ),
    status = if_else(is.na(death_year), "alive", "deceased"),
    death_year = if_else(is.na(death_year), 2027, death_year),
    known_for = if_else(
      name == "Rosalind Franklin",
      "understanding of the molecular structures of DNA ",
      known_for
    )
  ) |>
  pivot_longer(
    cols = contains("year"),
    names_to = "year_type",
    values_to = "year"
  ) |>
  mutate(death_year_fake = if_else(year == 2027, TRUE, FALSE))

scientists_longer
```

# Plot

```{r}
#| label: scientists-gantt-plot
#| echo: false
#| fig-asp: 0.6
#| out-width: "100%"
#| fig-width: 10
#| warning: false
ggplot(
  scientists_longer,
  aes(
    x = year,
    y = fct_reorder(name, as.numeric(factor(profession))),
    group = name,
    color = profession
  )
) +
  geom_point(aes(shape = death_year_fake), show.legend = FALSE) +
  geom_line(aes(linetype = status), show.legend = FALSE)
# more geoms: text
# scales
# coordinates
# faceting
# labels
# theme
```
